// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace PinguiWorld
{
public static class GPGSIds
{
        public const string leaderboard_monthly_ranking = "CgkI5721y58KEAIQCA"; // <GPGSID>
        public const string achievement_professional = "CgkI5721y58KEAIQBg"; // <GPGSID>
        public const string leaderboard_weekly_ranking = "CgkI5721y58KEAIQCQ"; // <GPGSID>
        public const string achievement_well_played = "CgkI5721y58KEAIQBA"; // <GPGSID>
        public const string achievement_stylish = "CgkI5721y58KEAIQAw"; // <GPGSID>
        public const string achievement_amateur = "CgkI5721y58KEAIQBQ"; // <GPGSID>
        public const string achievement_here_comes_the_money = "CgkI5721y58KEAIQAg"; // <GPGSID>
        public const string leaderboard_daily_ranking = "CgkI5721y58KEAIQCg"; // <GPGSID>
        public const string achievement_wowldwidechampion = "CgkI5721y58KEAIQBw"; // <GPGSID>
        public const string achievement_good_start = "CgkI5721y58KEAIQAQ"; // <GPGSID>

}
}
